import { RequirementSet, CertificateRecord, Requirement } from '../types';

export const PILOT_MDS_REQUIREMENT_SET: RequirementSet = {
  id: 'reqset-hawa-a105n-rev-a',
  clientName: 'Hawa Valves',
  materialGrade: 'ASTM A105N',
  mdsNumber: 'QE-F-CS-ASTM-A105-NACE-001-[N1151]',
  revision: 'Rev A',
  title: 'Client Material Data Sheet - Carbon Steel Forgings for Sour Service (ASTM A105N)',
  effectiveDate: '2025-01-15',
  status: 'approved',
  approvedBy: 'user-marcus-vance',
  approvedAt: '2025-01-15T09:00:00Z',
  organizationId: 'org-apex-01',
  requirements: [
    // Chemical composition
    {
      id: 'req-chem-c',
      category: 'chemical',
      field: 'C',
      displayName: 'Carbon (C)',
      operator: 'MAX',
      maxValue: 0.35,
      unit: '%',
      mandatory: true,
      description: 'Maximum Carbon content 0.35 wt%',
      clauseReference: 'Clause 3.1 & ASTM A105 Tab. 1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 2,
    },
    {
      id: 'req-chem-mn',
      category: 'chemical',
      field: 'Mn',
      displayName: 'Manganese (Mn)',
      operator: 'RANGE',
      minValue: 0.60,
      maxValue: 1.05,
      unit: '%',
      mandatory: true,
      description: 'Manganese content 0.60 to 1.05 wt%',
      clauseReference: 'Clause 3.1 & ASTM A105 Tab. 1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 2,
    },
    {
      id: 'req-chem-p',
      category: 'chemical',
      field: 'P',
      displayName: 'Phosphorus (P)',
      operator: 'MAX',
      maxValue: 0.035,
      unit: '%',
      mandatory: true,
      description: 'Maximum Phosphorus content 0.035 wt%',
      clauseReference: 'Clause 3.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 2,
    },
    {
      id: 'req-chem-s',
      category: 'chemical',
      field: 'S',
      displayName: 'Sulfur (S)',
      operator: 'MAX',
      maxValue: 0.035,
      unit: '%',
      mandatory: true,
      description: 'Maximum Sulfur content 0.035 wt%',
      clauseReference: 'Clause 3.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 2,
    },
    {
      id: 'req-chem-si',
      category: 'chemical',
      field: 'Si',
      displayName: 'Silicon (Si)',
      operator: 'RANGE',
      minValue: 0.10,
      maxValue: 0.35,
      unit: '%',
      mandatory: true,
      description: 'Silicon content 0.10 to 0.35 wt%',
      clauseReference: 'Clause 3.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 2,
    },
    {
      id: 'req-chem-ce',
      category: 'chemical',
      field: 'CE',
      displayName: 'Carbon Equivalent (CE)',
      operator: 'AGGREGATE',
      maxValue: 0.43,
      unit: '',
      mandatory: true,
      description: 'CE = C + Mn/6 + (Cr+Mo+V)/5 + (Ni+Cu)/15 max 0.43',
      clauseReference: 'Clause 3.2 & Supplementary S5',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 2,
      metallurgicalNotes: 'Calculated using IIW formula. Crucial for weldability and sour service resistance.',
    },
    // Heat Treatment
    {
      id: 'req-ht-condition',
      category: 'heat_treatment',
      field: 'heatTreatmentCondition',
      displayName: 'Heat Treatment Condition',
      operator: 'MATCH',
      targetValue: 'Normalized',
      mandatory: true,
      description: 'Material must be supplied in Normalized condition (ASTM A105N)',
      clauseReference: 'Clause 4.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 3,
    },
    {
      id: 'req-ht-temp',
      category: 'heat_treatment',
      field: 'normalizingTemperature',
      displayName: 'Normalizing Temperature',
      operator: 'RANGE',
      minValue: 900,
      maxValue: 960,
      unit: '°C',
      mandatory: true,
      description: 'Normalizing heat treatment temperature must be 900–960 °C',
      clauseReference: 'Clause 4.2',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 3,
      metallurgicalNotes: 'Austenitizing below 900°C produces incomplete grain refinement and substandard sour performance.',
    },
    // Mechanical Properties
    {
      id: 'req-mech-tensile',
      category: 'mechanical',
      field: 'tensileStrength',
      displayName: 'Tensile Strength',
      operator: 'MIN',
      minValue: 485,
      unit: 'MPa',
      mandatory: true,
      description: 'Minimum Tensile Strength 485 MPa (70 ksi)',
      clauseReference: 'Clause 5.1 & ASTM A105 Tab. 2',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 3,
    },
    {
      id: 'req-mech-yield',
      category: 'mechanical',
      field: 'yieldStrength',
      displayName: 'Yield Strength (0.2% Offset)',
      operator: 'MIN',
      minValue: 250,
      unit: 'MPa',
      mandatory: true,
      description: 'Minimum Yield Strength 250 MPa (36 ksi)',
      clauseReference: 'Clause 5.1 & ASTM A105 Tab. 2',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 3,
    },
    {
      id: 'req-mech-elongation',
      category: 'mechanical',
      field: 'elongation',
      displayName: 'Elongation (A5)',
      operator: 'MIN',
      minValue: 30,
      unit: '%',
      mandatory: true,
      description: 'Minimum Elongation 30%',
      clauseReference: 'Clause 5.1 (Enhanced ductility for sour service)',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 3,
      metallurgicalNotes: 'Client MDS imposes 30% min elongation, exceeding baseline ASTM A105 requirement of 22%.',
    },
    {
      id: 'req-mech-roa',
      category: 'mechanical',
      field: 'reductionOfArea',
      displayName: 'Reduction of Area',
      operator: 'MIN',
      minValue: 30,
      unit: '%',
      mandatory: true,
      description: 'Minimum Reduction of Area 30%',
      clauseReference: 'Clause 5.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 3,
    },
    // Hardness
    {
      id: 'req-hard-max',
      category: 'hardness',
      field: 'hardness',
      displayName: 'Hardness (HBW)',
      operator: 'MAX',
      maxValue: 187,
      unit: 'HBW',
      mandatory: true,
      description: 'Maximum Hardness 187 HBW (in accordance with NACE MR0175 / ISO 15156)',
      clauseReference: 'Clause 6.1 & NACE MR0175 Tab. A.2',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 4,
      metallurgicalNotes: 'Strict limit to prevent Sulfide Stress Cracking (SSC) in sour oil & gas environments.',
    },
    // NDE Requirements
    {
      id: 'req-nde-visual',
      category: 'nde',
      field: 'visualExamination',
      displayName: 'Visual Examination',
      operator: 'REQUIRED',
      mandatory: true,
      description: '100% Visual examination of all forgings per MSS-SP-55',
      clauseReference: 'Clause 7.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 4,
    },
    {
      id: 'req-nde-ut',
      category: 'nde',
      field: 'ultrasonicTesting',
      displayName: 'Ultrasonic Testing (UT)',
      operator: 'REQUIRED',
      mandatory: true,
      description: '100% Ultrasonic Testing (UT) per ASTM A388 / ASME Sec. V Art. 4',
      clauseReference: 'Clause 7.2',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 4,
      metallurgicalNotes: 'Mandatory volumetric inspection for high-pressure sour valve bodies.',
    },
    {
      id: 'req-nde-mpt',
      category: 'nde',
      field: 'magneticParticleTesting',
      displayName: 'Magnetic Particle Testing (MPT)',
      operator: 'REQUIRED',
      mandatory: true,
      description: '100% Magnetic Particle Examination (MPT) per ASTM A275',
      clauseReference: 'Clause 7.3',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 4,
    },
    // Certification & General
    {
      id: 'req-gen-forging-ratio',
      category: 'general',
      field: 'forgingRatio',
      displayName: 'Forging Reduction Ratio',
      operator: 'MIN',
      minValue: 3.0,
      unit: '',
      mandatory: true,
      description: 'Minimum Forging Reduction Ratio 3:1 from ingot/billet',
      clauseReference: 'Clause 2.2',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 2,
    },
    {
      id: 'req-gen-weld-repair',
      category: 'certification',
      field: 'weldRepair',
      displayName: 'Weld Repair Restriction',
      operator: 'FORBIDDEN',
      mandatory: true,
      description: 'Weld repair is strictly NOT permitted on raw forgings',
      clauseReference: 'Clause 8.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 5,
    },
    {
      id: 'req-cert-en10204',
      category: 'certification',
      field: 'en10204Type',
      displayName: 'Inspection Certificate Type',
      operator: 'MATCH',
      targetValue: 'EN 10204 3.1',
      mandatory: true,
      description: 'Inspection Certificate according to EN 10204 Type 3.1',
      clauseReference: 'Clause 9.1',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 5,
    },
    {
      id: 'req-cert-nace',
      category: 'certification',
      field: 'naceCompliance',
      displayName: 'NACE MR0175 / ISO 15156 Compliance Statement',
      operator: 'MATCH',
      targetValue: 'NACE MR0175',
      mandatory: true,
      description: 'Certificate must certify compliance with NACE MR0175 / ISO 15156',
      clauseReference: 'Clause 9.2',
      sourceDocument: 'Hawa MDS QE-F-CS-ASTM-A105-NACE-001 Rev A',
      sourcePage: 5,
    },
  ],
};

export const PILOT_SUPPLIER_MTC: CertificateRecord = {
  id: 'cert-ww2606229-3',
  documentId: 'doc-mtc-ww2606229-3',
  mtcNumber: 'WW2606229-3',
  supplierName: 'Western Forge & Flange Co.',
  clientName: 'Hawa Valves',
  poNumber: 'PO-774920',
  issueDate: '2025-02-10',
  materialGrade: 'ASTM A105 / A105N (ASME SA105N)',
  standard: 'ASTM A105 / A105M-21, ASME B16.5, NACE MR0175/ISO 15156',
  heats: ['A228', 'YBA'],
  parts: ['2" 600# WN Flange Sch 80', '4" 600# Blind Flange'],
  productType: 'Carbon Steel Forged Flanges',
  certifiedBy: 'J. Henderson - Quality Assurance Directorate',
  en10204Type: 'EN 10204 3.1',
  evidenceItems: [
    // === Heat A228 Chemistry ===
    {
      id: 'ev-a228-c',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'chemical',
      field: 'C',
      displayName: 'Carbon (C)',
      rawValue: '0.21 %',
      normalizedValue: 0.21,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat A228 Ladle Analysis: C: 0.21%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-mn',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'chemical',
      field: 'Mn',
      displayName: 'Manganese (Mn)',
      rawValue: '0.88 %',
      normalizedValue: 0.88,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat A228 Ladle Analysis: Mn: 0.88%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-p',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'chemical',
      field: 'P',
      displayName: 'Phosphorus (P)',
      rawValue: '0.012 %',
      normalizedValue: 0.012,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat A228 Ladle Analysis: P: 0.012%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-s',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'chemical',
      field: 'S',
      displayName: 'Sulfur (S)',
      rawValue: '0.008 %',
      normalizedValue: 0.008,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat A228 Ladle Analysis: S: 0.008%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-si',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'chemical',
      field: 'Si',
      displayName: 'Silicon (Si)',
      rawValue: '0.24 %',
      normalizedValue: 0.24,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat A228 Ladle Analysis: Si: 0.24%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-ce',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'chemical',
      field: 'CE',
      displayName: 'Carbon Equivalent (CE)',
      rawValue: '0.37',
      normalizedValue: 0.37,
      unit: '',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat A228 Reported Carbon Equivalent CE: 0.37',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    // Heat A228 Heat Treatment
    {
      id: 'ev-a228-ht-cond',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'heat_treatment',
      field: 'heatTreatmentCondition',
      displayName: 'Heat Treatment Condition',
      rawValue: 'Normalized at 910°C, air cooled',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Thermal History: Normalized condition, soaked 2.5 hrs, still air cooled',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-ht-temp',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'heat_treatment',
      field: 'normalizingTemperature',
      displayName: 'Normalizing Temperature',
      rawValue: '910 °C',
      normalizedValue: 910,
      unit: '°C',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Normalizing cycle: 910 °C (+/- 10°C), soak time: 150 mins',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    // Heat A228 Mechanical
    {
      id: 'ev-a228-tensile',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'mechanical',
      field: 'tensileStrength',
      displayName: 'Tensile Strength',
      rawValue: '542 MPa',
      normalizedValue: 542,
      unit: 'MPa',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat A228: Tensile Rm = 542 N/mm2 (MPa)',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-yield',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'mechanical',
      field: 'yieldStrength',
      displayName: 'Yield Strength',
      rawValue: '318 MPa',
      normalizedValue: 318,
      unit: 'MPa',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat A228: Yield Re = 318 N/mm2 (MPa)',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-elongation',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'mechanical',
      field: 'elongation',
      displayName: 'Elongation',
      rawValue: '32 %',
      normalizedValue: 32,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat A228: Elongation A5 = 32%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-roa',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'mechanical',
      field: 'reductionOfArea',
      displayName: 'Reduction of Area',
      rawValue: '48 %',
      normalizedValue: 48,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat A228: Reduction of Area Z = 48%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-a228-hardness',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'A228',
      category: 'hardness',
      field: 'hardness',
      displayName: 'Hardness',
      rawValue: '143 HBW',
      normalizedValue: 143,
      unit: 'HBW',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Hardness Testing: 143 HBW (10/3000)',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },

    // === Heat YBA Chemistry ===
    {
      id: 'ev-yba-c',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'chemical',
      field: 'C',
      displayName: 'Carbon (C)',
      rawValue: '0.22 %',
      normalizedValue: 0.22,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat YBA Ladle Analysis: C: 0.22%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-mn',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'chemical',
      field: 'Mn',
      displayName: 'Manganese (Mn)',
      rawValue: '0.91 %',
      normalizedValue: 0.91,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat YBA Ladle Analysis: Mn: 0.91%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-p',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'chemical',
      field: 'P',
      displayName: 'Phosphorus (P)',
      rawValue: '0.014 %',
      normalizedValue: 0.014,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat YBA Ladle Analysis: P: 0.014%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-s',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'chemical',
      field: 'S',
      displayName: 'Sulfur (S)',
      rawValue: '0.009 %',
      normalizedValue: 0.009,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat YBA Ladle Analysis: S: 0.009%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-si',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'chemical',
      field: 'Si',
      displayName: 'Silicon (Si)',
      rawValue: '0.22 %',
      normalizedValue: 0.22,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat YBA Ladle Analysis: Si: 0.22%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-ce',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'chemical',
      field: 'CE',
      displayName: 'Carbon Equivalent (CE)',
      rawValue: '0.39',
      normalizedValue: 0.39,
      unit: '',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Heat YBA Reported Carbon Equivalent CE: 0.39',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    // Heat YBA Heat Treatment (CRITICAL DEVIATION: 890°C < 900°C)
    {
      id: 'ev-yba-ht-cond',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'heat_treatment',
      field: 'heatTreatmentCondition',
      displayName: 'Heat Treatment Condition',
      rawValue: 'Normalized at 890°C, air cooled',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Thermal History: Normalized condition, soaked 2.0 hrs, air cooled',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-ht-temp',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'heat_treatment',
      field: 'normalizingTemperature',
      displayName: 'Normalizing Temperature',
      rawValue: '890 °C',
      normalizedValue: 890,
      unit: '°C',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Normalizing cycle: 890 °C, soak duration: 120 mins',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    // Heat YBA Mechanical (CRITICAL DEVIATION: Elongation 29% < 30%)
    {
      id: 'ev-yba-tensile',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'mechanical',
      field: 'tensileStrength',
      displayName: 'Tensile Strength',
      rawValue: '515 MPa',
      normalizedValue: 515,
      unit: 'MPa',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat YBA: Tensile Rm = 515 N/mm2 (MPa)',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-yield',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'mechanical',
      field: 'yieldStrength',
      displayName: 'Yield Strength',
      rawValue: '295 MPa',
      normalizedValue: 295,
      unit: 'MPa',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat YBA: Yield Re = 295 N/mm2 (MPa)',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-elongation',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'mechanical',
      field: 'elongation',
      displayName: 'Elongation',
      rawValue: '29 %',
      normalizedValue: 29,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat YBA: Elongation A5 = 29%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-roa',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'mechanical',
      field: 'reductionOfArea',
      displayName: 'Reduction of Area',
      rawValue: '42 %',
      normalizedValue: 42,
      unit: '%',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Mechanical Test Heat YBA: Reduction of Area Z = 42%',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-yba-hardness',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'YBA',
      category: 'hardness',
      field: 'hardness',
      displayName: 'Hardness',
      rawValue: '149 HBW',
      normalizedValue: 149,
      unit: 'HBW',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Hardness Testing: 149 HBW (10/3000)',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },

    // === General & Certification Statements ===
    {
      id: 'ev-gen-visual',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'GENERAL',
      category: 'nde',
      field: 'visualExamination',
      displayName: 'Visual Examination',
      rawValue: '100% Visual and dimensional examination performed per MSS-SP-55 - Satisfactory',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Inspection Statement: 100% Visual and dimensional check carried out. Results: PASS.',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-gen-forging-ratio',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'GENERAL',
      category: 'general',
      field: 'forgingRatio',
      displayName: 'Forging Reduction Ratio',
      rawValue: '4.2 : 1',
      normalizedValue: 4.2,
      unit: '',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Manufacturing process: Forged from continuously cast bloom. Minimum forging reduction ratio: 4.2 to 1.',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-gen-weld-repair',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'GENERAL',
      category: 'certification',
      field: 'weldRepair',
      displayName: 'Weld Repair Restriction',
      rawValue: 'We certify that all forgings were produced entirely without weld repair.',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Certification Note 3: Forgings supplied free of any weld repair.',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-gen-en10204',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'GENERAL',
      category: 'certification',
      field: 'en10204Type',
      displayName: 'Inspection Certificate Type',
      rawValue: 'EN 10204 Type 3.1 Inspection Certificate',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 1,
      snippet: 'Header: INSPECTION CERTIFICATE TYPE 3.1 EN 10204:2004',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    {
      id: 'ev-gen-nace',
      certificateId: 'cert-ww2606229-3',
      heatNo: 'GENERAL',
      category: 'certification',
      field: 'naceCompliance',
      displayName: 'NACE MR0175 Compliance',
      rawValue: 'Material conforms to NACE MR0175 / ISO 15156-2 hardness and heat treatment provisions for sour service.',
      sourceDocument: 'Supplier MTC WW2606229-3',
      sourcePage: 2,
      snippet: 'Standards compliance clause: NACE MR0175 / ISO 15156 Table A.2 compliant.',
      confidence: 'high',
      extractedAt: '2025-02-10T14:30:00Z',
    },
    // Note: Ultrasonic (UT) and Magnetic Particle (MPT) are intentionally NOT present in evidence to produce DOCUMENTATION GAP!
  ],
};
